services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_ir_captcha_example
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./database:/var/www/database
    ports:
      - "9000:9000"
    environment:
      - APP_URL=http://localhost:8000
    networks:
      - laravel_net

  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
